### ISSUE TITLE
update on the state-of-the-art

### ISSUE THREAD

**Issue by usccolumbia** [YKQ98/Matformer#1]
For tasks of Bulk Moduli and Shear Moduli, we follow GATGNN, the recent state-of-the-art method for these two tasks, and use the same training, validation, and test sets, including 4664, 393, and 393 crystals.
===
GATGNN  is NOT true state of the art algo for this
You may want to try with the latest model
https://github.com/usccolumbia/deeperGATGNN

**Comment by YKQ98** [comment]
Thank you for the information. 
This paper you mentioned is published (April 27, 2022) near the submission deadline of NeurIPS (May 19, 2022), and not included as a baseline method. 
We will include this baseline for future works.
