### ISSUE TITLE
strange band gap results 

### ISSUE THREAD

**Issue by ychen739** [YKQ98/Matformer#10]
Hi!
I was trying to run an exp on band gap prediction. But I got some strange numbers that differ a lot from what you got in the paper.
Do you have any thoughts on this? Thanks!
![image](https://github.com/YKQ98/Matformer/assets/119469864/c1857138-573b-4c21-a89c-f55ec1d4e0c5)

**Comment by YKQ98** [comment]
What is this dataset?

**Comment by ychen739** [comment]
This is for MP. Should I modify some code snippets? (I was using the saved dataloader, which is the same as when I run mp formation energy, by setting save_dataloader=True.) thanks for your help!

**Comment by YKQ98** [comment]
I suggest you do not save the data loader for different tasks. It will influence the target value.

**Comment by ychen739** [comment]
got it. I think that should be the case. thank you!
