### ISSUE TITLE
follow up on shear/bulk modulus

### ISSUE THREAD

**Issue by ychen739** [YKQ98/Matformer#11]
Also I would like to ask if you can provide a brief guideline on how can we revise the code/config to reproduce the numbers as in the paper and where should we put the dataset files in. Thanks a bunch!

**Comment by YKQ98** [comment]
Thank you for your interest. The code itself can reproduce the results for most of the tasks shown in the paper. Just run it as shown in the readme.

**Comment by ychen739** [comment]
thanks! I found somewhere I should set mp_id_list to run the other two datasets. will close this issue.
