### ISSUE TITLE
reproduction of MP e_form

### ISSUE THREAD

**Issue by 292916808** [YKQ98/Matformer#12]
Hi, thanks for providing the nice codebase! I am currently trying to reproduce the results on MP e_form. However, I can only get a list of ckpts like the one below and the test MAE is around 0.91. The other tasks on MP didn't have a similar issue and the numbers look correct.
![image](https://github.com/YKQ98/Matformer/assets/75068767/f8da5de0-9b73-40d1-9b5e-862d1974a7ad)
![image](https://github.com/YKQ98/Matformer/assets/75068767/b94b0564-7ada-47b4-8b26-446a2afeefb0)

Do you have any thoughts of this?
Thank you!

**Comment by YKQ98** [comment]
What learning rate are you using?

**Comment by 292916808** [comment]
it's 0.01 as default

**Comment by YKQ98** [comment]
It is the training failure of some random seed, the validation never gets better after 190 epoch. I suggest you take a different random seed, or decrease learning rate to 0.008 to stabilize it.

**Comment by 292916808** [comment]
Oh I meant 0.001 as the default value (sorry about the typo). So it would be 0.0008 after decreasing right?

**Comment by YKQ98** [comment]
What about using the code directly, with the default learning rate scheduler? I set everything up in the code and it should be fine to use the default settings.

**Comment by 292916808** [comment]
Yeah, but I was indeed using the default setting... I will try tuning lr a bit and see if I can reproduce it.
