### ISSUE TITLE
pydantic.errors.

### ISSUE THREAD

**Issue by Jbangliang** [YKQ98/Matformer#14]
Hello, I configured the environment according to your documentation, but I encountered an error when running the script."
I have searched for a long time, but the problem has not been resolved.

**Comment by Jbangliang** [comment]
![QQ图片20240607121916](https://github.com/YKQ98/Matformer/assets/136157142/6f69df04-9229-42ae-a47e-48d4ba2f4483)

**Comment by YKQ98** [comment]
As you can see in the error message, maybe you can try to import BaseSettings from pydantic-settings package instead.

**Comment by YKQ98** [comment]
If the problem is solved, I will close this issue as complete.
