### ISSUE TITLE
Inquiry on your dataset

### ISSUE THREAD

**Issue by Breaddsmall** [YKQ98/Matformer#2]
I am interested in your work and I really appreciate your efforts in retraining all the baseline models on the same datasets.  I would like to know that would you publish your datasets as well as the codes? Thank you very much!

**Comment by YKQ98** [comment]
Thank you for the interest!
The code of Matformer and corresponding dataset will be released early 2023 according to our plan.

**Comment by Breaddsmall** [comment]
> 



> Thank you for the interest! The code of Matformer and corresponding dataset will be released early 2023 according to our plan.

Thank you very much! And I guess that this is the same dataset used in your work? https://figshare.com/collections/ALIGNN_data/5429274 Thanks again!

**Comment by YKQ98** [comment]
Yes, for the formation energy and band gap tasks in MP and all five tasks in Jarvis, they are the same as ALIGNN, with the same splits. For the other two tasks in MP, they are the same as another baseline method.

**Comment by Breaddsmall** [comment]
> 

Thanks for the reply!

**Comment by Breaddsmall** [comment]
Sorry, but I couldn't find the original split of datasets used by ALIGNN. Did you use random_seed 123 to shuffle the MP and JARVIS data? (Also, did you use random seed 456 in that subset same as GATGNN?) This would be very helpful! Thank you very much!

**Comment by YKQ98** [comment]
You can use directly the same data preprocessing and loading code without changing the random seed to obtain the original splits used by ALIGNN. And this can be found in their official code in GitHub.  For the GATGNN, we use their released datasets. If you want to use these splits now, it is better to do the above.

**Comment by Breaddsmall** [comment]
That's very informative! Thank you very much!

**Comment by YKQ98** [comment]
Now you can use the official code, thank you.
