### ISSUE TITLE
Single crystal structure predicts formation energy

### ISSUE THREAD

**Issue by SomehandYF** [YKQ98/Matformer#3]
Hello, I would like to ask how the crystal structure of a cif file can predict the formation energy after I have trained a crystal structure and formation energy model and obtained .pt file. Can you write some code? Thank you very much!

**Comment by YKQ98** [comment]
Thanks for the interest in our work!

Could you please check the code in the train.py from line 294 to line 332? You may get some ideas of how to conduct the evaluation after the model is trained.

**Comment by SomehandYF** [comment]
I have solved the problem, thank you very much for your reply！
