### ISSUE TITLE
Running command issue

### ISSUE THREAD

**Issue by sadmanomee** [YKQ98/Matformer#4]
In the Training and Prediction section, there is a command called "python setup.py". But it needs an additional argument. Also, there is no train.py folder in both the dataset directory.

**Comment by YKQ98** [comment]
Do you still have these questions? Or you already solved them?

**Comment by sadmanomee** [comment]
should I do a "python setup.py install" instead?

**Comment by YKQ98** [comment]
you can add these two lines in the train_mp.py instead of using setup.py
import sys
sys.path.append("/yourpath/Matformer")

**Comment by sadmanomee** [comment]
Thank you !
