### ISSUE TITLE
Error in converting to training config!

### ISSUE THREAD

**Issue by sadmanomee** [YKQ98/Matformer#5]
I get an exception at line 132 in matformer/train.py file when I try to run the code. The exception prints as follows - "Check 'model'
error in converting to training config!". The problem is the config dictionary cannot be converted to the TrainingConfig type object. Can you please take a look at it?

**Comment by YKQ98** [comment]
Thank you for pointing this, just change the original code in train_mp.py to this:
train_prop_model(learning_rate=0.001,name="matformer",
and this problem will be solved.

**Comment by sadmanomee** [comment]
Thank you, this problem is solved.
