### ISSUE TITLE
Issue of Reproducing the results

### ISSUE THREAD

**Issue by shrimonmuke0202** [YKQ98/Matformer#6]
How to reproduce the result for shear modulus for the Material project dataset, when I run this code train_mp.py by changing prop[0] to prop[-1] and epochs to 300 I got 16.347 MAE. I also convert the GPa to log(GPa), also I got the same type of MAE score.

**Comment by YKQ98** [comment]
For the shear moduli and bulk moduli, it is not a direct use of this code, due to the fact that the dataset settings follow GATGNN instead of ALIGNN. 
I'm planning to release the dataset of GATGNN soon, if you need it now, you can use the GATGNN released datasets and get the corresponding results.

**Comment by ychen739** [comment]
Hi @YKQ98! Just wanted to know when you're going to release your code/dataset for the GATGNN settings. Thanks! : )

**Comment by ychen739** [comment]
Also, I notice there is an argument 'Voronoi' for 'neighbor_strategy' but you didn't implement it. What kind of strategy does it refer to? Have you tried it by any chance and how does it perform? Thanks!

**Comment by YKQ98** [comment]
The datasets are now published at https://figshare.com/projects/Bulk_and_shear_datasets/165430

**Comment by ychen739** [comment]
Thank you!
