### ISSUE TITLE
train MAE stays -1

### ISSUE THREAD

**Issue by ychen739** [YKQ98/Matformer#7]
Hi @YKQ98 !

Thanks for this nice repo! I was training on MP e_form but I kept getting -1 for train MAE. Do you have any suggestions/explanations about this? Looking forward to your reply.
<img width="130" alt="112233" src="https://user-images.githubusercontent.com/119469864/233756986-0d8f646f-1b88-4ef6-a916-e819cd149eb1.png">

**Comment by YKQ98** [comment]
Thanks for using our model, this is because I omit the Mae calculation of train set to speed up the training process, -1 is a value I set, as long as you see a normal loss and validation Mae, it is fine.

**Comment by ychen739** [comment]
Thank you!
