### ISSUE TITLE
neighbor strategy

### ISSUE THREAD

**Issue by ychen739** [YKQ98/Matformer#8]
Hi, @YKQ98! I asked the questions in another thread, but you might not see them. So, I open an issue here to ask them again. Sorry for bothering you! 
I notice there is an argument 'Voronoi' for 'neighbor_strategy' but you didn't implement it. What kind of strategy does it refer to? Have you tried it by any chance and how does it perform? Thanks!

**Comment by YKQ98** [comment]
It is some legacy code from previous code base ALIGNN, please do not use and just use the methods mentioned in our mat former paper. 

Thank you for your interest.

**Comment by ychen739** [comment]
Thanks!
